# Generated by Django 5.0.6 on 2024-05-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_business_type_userprofile_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shop',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
