# Generated by Django 5.0.6 on 2024-07-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='business_type',
            field=models.CharField(choices=[('supplier', 'Raw Material Supplier'), ('customer', 'Customer')], default='customer', max_length=50),
        ),
    ]
