# Generated by Django 5.0.6 on 2024-05-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='purchasedproduct',
            name='price',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
