# Generated by Django 5.0.6 on 2024-05-30 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_price_purchasedproduct_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('raw_material_1', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_1', models.IntegerField(blank=True, null=True)),
                ('raw_material_2', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_2', models.IntegerField(blank=True, null=True)),
                ('raw_material_3', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_3', models.IntegerField(blank=True, null=True)),
                ('raw_material_4', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_4', models.IntegerField(blank=True, null=True)),
                ('raw_material_5', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_5', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('required_quantity', models.IntegerField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial')),
            ],
        ),
    ]
