# Generated by Django 5.0.6 on 2024-07-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cartitem_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingproduct',
            name='quantity_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingproduct',
            name='quantity_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingproduct',
            name='quantity_3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingproduct',
            name='quantity_4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingproduct',
            name='quantity_5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
