# Generated by Django 5.0.6 on 2024-07-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_manufacturingproduct_raw_material_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='complete', max_length=20),
        ),
    ]
