# Generated by Django 5.0.6 on 2024-07-22 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_items',
        ),
        migrations.CreateModel(
            name='ProductRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial')),
            ],
            options={
                'unique_together': {('product', 'raw_material')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='raw_materials',
            field=models.ManyToManyField(through='core.ProductRawMaterial', to='core.rawmaterial'),
        ),
    ]
